// <auto-generated />
using System;
using Kasbotech_AvgCandle.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kasbotech_AvgCandle.Migrations
{
    [DbContext(typeof(CandleDataBaseContext))]
    partial class CandleDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kasbotech_AvgCandle.Model.Entities.Candle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CandleAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CandleClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CandleHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CandleLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CandleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CandleOpen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candles");
                });
#pragma warning restore 612, 618
        }
    }
}
